name: Build ArmorPaint iOS

on: [push, pull_request]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for iOS
        run: |
          cd paint/build
          xcodebuild -project ArmorPaint.xcodeproj \
                     -scheme ArmorPaint \
                     -sdk iphoneos \
                     -configuration Release
      - name: Export .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmorPaint-iOS
          path: paint/build/Release-iphoneos/*.app

